# -*- coding: utf-8 -*-
"""Conditionals.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZU_g02LxPugeoY29hlswwWbEGbVPuKy5
"""

#Problem 01
#Positive, negative, or zero
#Take a number as input. Print whether it is positive, negative, or zero. Simple if-elif-else — get your fingers moving.

number = int(input("Enter a number: "))
if number > 0:
    print("The number is positive.")
elif number < 0:
    print("The number is negative.")
else:
    print("The number is zero.")

#Problem 02
#Even or odd
#Take a number as input. Print whether it is even or odd. Also print whether it is divisible by 5. Two separate checks.

number = int(input("Enter a number: "))
if number % 2 == 0:
    print("The number is even.")
else:
    print("The number is odd.")
if number % 5 == 0:
    print("The number is divisible by 5.")
else:
    print("The number is not divisible by 5.")

#Problem 03
#Voting eligibility
#Take age as input. Print whether the person can vote, is too young to vote, or is a senior citizen (65+). Make sure all age ranges are covered with no gaps.

age = int(input("Enter your age: "))
if age < 18:
    print("You are too young to vote.")
elif age >= 18 and age < 65:
    print("You are eligible to vote.")
else:
    print("You are a senior citizen.")

#Problem 04
#Grade calculator
#Take marks (0–100) as input. Print the letter grade: A (90–100), B (75–89), C (60–74), D (45–59), F (below 45). Also print 'Invalid' if marks are outside 0–100.

marks = int(input("Enter your marks: "))
if marks < 0 or marks > 100:
    print("Invalid")
elif marks >= 90:
    print("A")
elif marks >= 75 and marks < 90:
    print("B")
elif marks >= 60 and marks < 75:
    print("C")
elif marks >= 45 and marks < 60:
    print("D")
elif marks < 45:
    print("F")
else:
    print("Invalid")

#Problem 05
#Electricity bill calculator
#Units consumed: 0–100 units @ ₹5/unit, 101–300 @ ₹8/unit, above 300 @ ₹12/unit. Take units as input, calculate and print the total bill. Add a surcharge of 10% if bill exceeds ₹2000.

units = int(input("Enter the number of units consumed: "))
if units <= 100 and units >= 0:
    bill = units * 5
elif units <= 300:
    bill = 100 * 5 + (units - 100) * 8
else:
    bill = 100 * 5 + 200 * 8 + (units - 300) * 12

if bill > 2000:
    bill = bill * 1.1

print(f"Total bill: ₹{bill}")

#Problem 06
#Leap year checker
#Take a year as input. Print whether it is a leap year or not. A year is a leap year if: divisible by 4, EXCEPT centuries (divisible by 100) which must also be divisible by 400.

year = int(input("Enter a year: "))
if (year % 4 == 0 and year % 100 != 0) or (year % 400 == 0):
    print(f"{year} is a leap year.")
else:
    print(f"{year} is not a leap year.")

#Problem 07
#Triangle validator
#Take three sides as input. First check if they form a valid triangle (sum of any two sides must be greater than the third). If valid, classify it: equilateral, isosceles, or scalene.

side_1 = int(input("Enter the first side: "))
side_2 = int(input("Enter the second side: "))
side_3 = int(input("Enter the third side: "))

if side_1 + side_2 > side_3 and side_1 + side_3 > side_2 and side_2 + side_3 > side_3:
    if side_1 == side_2 == side_3:
        print("Equilateral")
    elif side_1 == side_2 or side_1 == side_3 or side_2 == side_3:
        print("Isosceles")
    else:
        print("Scalene")
else:
    print("Not a valid triangle")

#Problem 08
#Simple ATM
#Set a balance and a PIN. Take PIN input — if wrong, print 'Access denied'. If correct, ask for withdrawal amount. Check if sufficient balance exists. Print updated balance or 'Insufficient funds'.

PIN = 224422
balance = 10000
PIN = int(input("Enter your PIN: "))

if PIN != 224422:
   print("Access denied")
else :

   withdrawal = int(input("Enter the amount to withdraw: "))
   if withdrawal > balance:
      print("Insufficient funds")
   else:
      balance = balance - withdrawal
      print("Your updated balance is: ", balance)

#Problem 09
#Season and weather advisor
#Take month (1–12) and temperature as input. Print the season (summer/monsoon/winter/spring). Then based on season AND temperature, print one clothing recommendation. Use both conditions together.

month = int(input("Enter the month (1-12): "))
temperature = int(input("Enter the temperature: "))
print("Month: ", month)
print("Temperature: ", temperature)
if month == 11 or month == 12 or month == 1 or month == 2:
    season = "Winter"
elif month ==4 or month ==5 or month==6:
    season = "Summer"
elif month == 7 or month == 8 or month ==9 :
    season = "Monsoon"
else:
    season = "Spring"

print(f"Season: {season}")

if season == "Winter" and temperature < 15:
    print("Wear a woolen sweater")
elif season == "Winter" and temperature >= 15:
    print("Wear a light sweater")
elif season == "Summer" and temperature < 15:
    print("Wear light jacket")
elif season == "Summer" and temperature >= 15:
    print("Wear light colored cotton clothes and a scarf")
elif season == "Monsoon" and temperature < 15:
    print("Wear a light jacket")
elif season == "Monsoon" and temperature >= 15:
    print("Wear a light jacket and a scarf and keep a raincoat")
elif season == "Spring" and temperature < 15:
    print("Wear a light t-shirts and tops")
elif season == "Spring" and temperature >= 15:
    print("Wear a light cotton clothes and a scarf")

#Problem 10
#College admission decider
#A college admits students based on: marks >= 85 AND age between 17–22, OR marks >= 75 AND has_scholarship = True. Take all inputs, print admitted or rejected, and a reason why.

age = int(input("Enter your age: "))
marks = int(input("Enter your marks: "))
has_scholarship = input("Do you have a scholarship? (True/False): ")

if marks >= 85 and 17 <= age <= 22:
    reason = "Marks >= 85 and age between 17-22"
elif marks >= 75 and has_scholarship == "True":
    reason = "Marks >= 75 and has scholarship"
elif marks >= 75 and has_scholarship == "True" and not (17 <= age <= 22):
    reason = "Scholarship criteria met but age is not in valid range"
else:
    reason = "Did not meet any admission criteria"

if (marks >= 85 and 17 <= age <= 22) or (marks >= 75 and has_scholarship == "True"):
    print("Admitted")

else:
    print("Rejected")

print(f"Reason: {reason}")