# -*- coding: utf-8 -*-
"""Dictionary.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XWoZ5w2mw4y_Ejgc8_EuGDrzW2GFv5Ct
"""

#Problem 01
#Dict basics
#Create a dictionary with 5 key-value pairs about yourself (name, age, city, course, hobby). Print the full dict, access 3 specific keys, update one value, and add a new key. Print after each change.

myself = {
    "name": "Hiya",
    "age": 18,
    "city": "Rajkot",
    "course": "Computer Engineering",
    "hobby": "Reading"
}

print(myself)

print(myself["name"])
print(myself["city"])
print(myself["course"])

myself["hobby"] = "Coding"
print(myself)

myself["email"] = "hiya@gmail.com"
print(myself)

#Problem 02
#Dict methods
#Using the same dictionary, print all keys, all values, and all key-value pairs. Check if 'email' exists in the dict. Use .get() to safely access a key that doesn't exist — compare it to direct access.

myself = {
    "name": "Hiya",
    "age": 18,
    "city": "Rajkot",
    "course": "Computer Engineering",
    "hobby": "Coding"
}

print(myself.keys())
print(myself.values())
print(myself.items())

print("email" in myself)

print(myself.get("email"))

# Direct access
# print(myself["email"])   # Gives error

#Problem 03
#Word frequency counter
#Take a sentence as a string. Count how many times each word appears. Store the result in a dictionary and print it sorted by frequency (most common first).

sentence = "python is easy and python is powerful"

words = sentence.split()
freq = {}

for word in words:
    freq[word] = freq.get(word, 0) + 1

sorted_freq = sorted(freq.items(), key=lambda x: x[1], reverse=True)

print(sorted_freq)

#Problem 04
#Student grade book
#Create a dict where keys are student names and values are lists of marks (3 subjects each). Calculate and print each student's average. Print the name of the top scoring student.

students = {
    "Aman": [80, 85, 90],
    "Riya": [95, 88, 92],
    "Karan": [70, 75, 72]
}

top_student = ""
highest_avg = 0

for name, marks in students.items():
    avg = sum(marks) / len(marks)
    print(name, "Average =", avg)

    if avg > highest_avg:
        highest_avg = avg
        top_student = name

print("Top Student:", top_student)

#Problem 05
#Dict as a phonebook
#Build a phonebook using a dictionary. Add 5 contacts. Write a search feature — take a name as input, print the number or 'Contact not found'. Add a delete feature. Print the phonebook before and after deletion.

phonebook = {
    "Aman": "1111",
    "Riya": "2222",
    "Karan": "3333",
    "Neha": "4444",
    "Jay": "5555"
}

print(phonebook)

name = input("Enter name: ")

if name in phonebook:
    print(phonebook[name])
else:
    print("Contact not found")

del_name = input("Enter name to delete: ")

if del_name in phonebook:
    del phonebook[del_name]

print(phonebook)

#Problem 06
#Nested dictionary
#Create a nested dictionary for 3 students, each with keys: name, age, and marks (which is itself a dict of subject:score pairs). Print each student's details and their highest scoring subject.

students = {
    1: {
        "name": "Aman",
        "age": 18,
        "marks": {"Math": 90, "Science": 85}
    },

    2: {
        "name": "Riya",
        "age": 19,
        "marks": {"Math": 95, "Science": 92}
    },

    3: {
        "name": "Jay",
        "age": 18,
        "marks": {"Math": 80, "Science": 88}
    }
}

for student in students.values():
    print(student["name"], student["age"])

    marks = student["marks"]

    highest = max(marks, key=marks.get)

    print("Highest Subject:", highest)

#Problem 07
#Dict comprehension
#Using dict comprehension, create: a dict of numbers 1–10 mapped to their squares, a dict of words mapped to their lengths from a sentence, and invert a given dictionary (swap keys and values).
#mediumShow hint

squares = {x: x*x for x in range(1, 11)}
print(squares)

sentence = "python makes coding easy"

lengths = {word: len(word) for word in sentence.split()}
print(lengths)

data = {"a": 1, "b": 2, "c": 3}

inverted = {v: k for k, v in data.items()}

print(inverted)

#Problem 08
#Inventory manager
#Create an inventory dict with item names as keys and quantities as values. Write logic to: add new items, restock existing items, sell items (reduce quantity), and print a warning for items with quantity below 5.

inventory = {
    "Pen": 10,
    "Book": 3,
    "Bag": 7
}

inventory["Bottle"] = 5

inventory["Book"] += 10

inventory["Pen"] -= 4

print(inventory)

for item, qty in inventory.items():
    if qty < 5:
        print(item, "is low in stock")

#Problem 09
#Frequency analyser
#Take a paragraph as input. Count character frequency (letters only, case-insensitive). Print the top 5 most common characters. Then count word frequency and print the top 3 most common words.
#hardShow hint

paragraph = input("Enter paragraph: ").lower()

char_freq = {}
word_freq = {}

for ch in paragraph:
    if ch.isalpha():
        char_freq[ch] = char_freq.get(ch, 0) + 1

words = paragraph.split()

for word in words:
    word_freq[word] = word_freq.get(word, 0) + 1

top_chars = sorted(char_freq.items(), key=lambda x: x[1], reverse=True)

print("Top 5 Characters:")
print(top_chars[:5])

top_words = sorted(word_freq.items(), key=lambda x: x[1], reverse=True)

print("Top 3 Words:")
print(top_words[:3])

#Problem 10
#Mini contacts app
#Build a complete contacts manager using a dict. Features: add contact (name, phone, email), view all contacts, search by name, update a contact's details, delete a contact. Use a while loop menu to keep it running until the user exits.

contacts = {}

while True:

    print("\n1.Add")
    print("2.View")
    print("3.Search")
    print("4.Update")
    print("5.Delete")
    print("6.Exit")

    choice = input("Enter choice: ")

    if choice == "1":
        name = input("Name: ")

        contacts[name] = {
            "phone": input("Phone: "),
            "email": input("Email: ")
        }

    elif choice == "2":
        for name, info in contacts.items():
            print(name, info)

    elif choice == "3":
        name = input("Enter name: ")

        if name in contacts:
            print(contacts[name])
        else:
            print("Not found")

    elif choice == "4":
        name = input("Enter name: ")

        if name in contacts:
            contacts[name]["phone"] = input("New phone: ")
            contacts[name]["email"] = input("New email: ")

    elif choice == "5":
        name = input("Enter name: ")

        if name in contacts:
            del contacts[name]

    elif choice == "6":
        break

    else:
        print("Invalid choice")