# -*- coding: utf-8 -*-
"""Functions.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HTzwN6BIYuAfc9k4Eh2klo4LdnyQKVo0
"""

#Problem 01
#Your first functions
#Write 3 simple functions: one that greets a person by name, one that returns the square of a number, and one that checks if a number is even or odd. Call each function and print the results.

def greet(name):
    return "Hello " + name

def square(num):
    return num * num

def check(num):
    if num % 2 == 0:
        return "Even"
    return "Odd"

print(greet("Hiya"))
print(square(5))
print(check(7))

#Problem 02
#Default parameters
#Write a function that calculates simple interest. Parameters: principal, rate, time — with rate defaulting to 5 and time defaulting to 1. Call it 3 ways: all args, only principal, principal + rate.

def simple_interest(principal, rate=5, time=1):
    return (principal * rate * time) / 100

print(simple_interest(1000, 10, 2))

print(simple_interest(1000))

print(simple_interest(1000, 8))

#Problem 03
#Return multiple values
#Write a function that takes a list of numbers and returns the minimum, maximum, and average — all three at once. Print all three returned values with labels.

def details(numbers):
    minimum = min(numbers)
    maximum = max(numbers)
    average = sum(numbers) / len(numbers)

    return minimum, maximum, average

mn, mx, avg = details([10, 20, 30, 40])

print("Minimum:", mn)
print("Maximum:", mx)
print("Average:", avg)

#Problem 04
#*args — variable arguments
#Write a function that accepts any number of numbers and returns their sum. Then write one that accepts any number of strings and returns them joined with a separator. Call each with different numbers of arguments.

def total(*numbers):
    return sum(numbers)

print(total(1, 2, 3))
print(total(10, 20, 30, 40))

def join_words(*words):
    return " - ".join(words)

print(join_words("Python", "Java", "C"))

#Problem 05
#**kwargs — keyword arguments
#Write a function that builds and prints a student profile from keyword arguments. It should handle any combination of: name, age, course, city, cgpa. Print only the keys that were actually passed.

def student_profile(**details):

    for key, value in details.items():
        print(key, ":", value)

student_profile(
    name="Hiya",
    course="Computer Engineering",
    cgpa=8.5
)

#Problem 06
#Recursive function
#Write a recursive function to calculate factorial. Write another recursive function to calculate the Nth Fibonacci number. Print results for several inputs. Add a comment explaining what the base case does.

def factorial(n):

    if n == 1:
        return 1

    return n * factorial(n - 1)

print(factorial(5))

def fibonacci(n):

    if n <= 1:
        return n

    return fibonacci(n - 1) + fibonacci(n - 2)

print(fibonacci(6))
print(fibonacci(8))

#Problem 07
#Function as expense calculator
#Write a set of functions for an expense tracker: add_expense(expenses, item, amount), get_total(expenses), get_average(expenses), get_highest(expenses). Use a dict for expenses. Call all functions and print results.

def add_expense(expenses, item, amount):
    expenses[item] = amount

def get_total(expenses):
    return sum(expenses.values())

def get_average(expenses):
    return sum(expenses.values()) / len(expenses)

def get_highest(expenses):
    return max(expenses, key=expenses.get)

expenses = {}

add_expense(expenses, "Food", 500)
add_expense(expenses, "Travel", 1000)
add_expense(expenses, "Books", 700)

print(expenses)
print("Total:", get_total(expenses))
print("Average:", get_average(expenses))
print("Highest:", get_highest(expenses))

#Problem 08
#Lambda functions
#Write lambda functions for: squaring a number, checking if a string is a palindrome, converting celsius to fahrenheit. Then use a lambda with sorted() to sort a list of tuples by the second element.

square = lambda x: x * x
print(square(5))

palindrome = lambda s: s == s[::-1]
print(palindrome("madam"))

temp = lambda c: (c * 9/5) + 32
print(temp(30))

data = [("A", 3), ("B", 1), ("C", 2)]

sorted_data = sorted(data, key=lambda x: x[1])

print(sorted_data)

#Problem 09
#Scope and closures
#Demonstrate local vs global scope with examples. Write a function that modifies a global variable using the global keyword. Then write a closure — a function that returns another function that remembers a value.

count = 10

def show():

    value = 5
    print("Local:", value)

show()
print("Global:", count)


def change():
    global count
    count = 20

change()
print("Changed Global:", count)

def outer(msg):

    def inner():
        print(msg)

    return inner

hello = outer("Hello Python")

hello()

#Problem 10
#Mini calculator with functions
#Build a calculator where each operation (add, subtract, multiply, divide, power, modulo) is a separate function. Write a main() function that takes two numbers and an operator as input and calls the right function. Handle division by zero.

def add(a, b):
    return a + b

def subtract(a, b):
    return a - b

def multiply(a, b):
    return a * b

def divide(a, b):

    if b == 0:
        return "Cannot divide by zero"

    return a / b

def power(a, b):
    return a ** b

def modulo(a, b):
    return a % b


def main():

    a = float(input("Enter first number: "))
    b = float(input("Enter second number: "))

    op = input("Enter operator (+,-,*,/,**,%) : ")

    if op == "+":
        print(add(a, b))

    elif op == "-":
        print(subtract(a, b))

    elif op == "*":
        print(multiply(a, b))

    elif op == "/":
        print(divide(a, b))

    elif op == "**":
        print(power(a, b))

    elif op == "%":
        print(modulo(a, b))

    else:
        print("Invalid operator")

main()