# -*- coding: utf-8 -*-
"""List and Tuples.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YfZ2iWsTT-upP8La8TtYIe57d4cz6c_s
"""

#Problem 01
#List basics
#Create a list of 5 of your favourite movies. Print the full list, the first item, the last item, and the length. Then add one more movie and print the updated list.

movies = ["Inception", "The Matrix", "Interstellar", "The Dark Knight", "Parasite"]

print("Full list:", movies)

print("First item:", movies[0])

print("Last item:", movies[-1])

print("Length of list:", len(movies))

movies.append("Dune")

print("Updated list:", movies)

#Problem 02
#List operations
#Create a list of 8 numbers. Print the list sorted ascending and descending. Find and print the max, min, and sum. Then remove the largest number and print the updated list.

numbers = [42, 7, 13, 91, 24, 65, 3, 18]
print(f"Original list: {numbers}")

numbers.sort()
print(f"Sorted (Ascending): {numbers}")


numbers.sort(reverse=True)
print(f"Sorted (Descending): {numbers}")

print(f"Maximum: {max(numbers)}")
print(f"Minimum: {min(numbers)}")
print(f"Sum: {sum(numbers)}")

numbers.remove(max(numbers))

print(f"Updated list after removing max: {numbers}")

#Problem 03
#List slicing
#Create a list of numbers 1–10. Using slicing only (no loops), print: the first 3 elements, the last 3 elements, every other element, and the list in reverse.

numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
print(f"Full list: {numbers}")

print(f"First 3: {numbers[:3]}")

print(f"Last 3: {numbers[-3:]}")

print(f"Every other: {numbers[::2]}")

print(f"Reversed: {numbers[::-1]}")

#Problem 04
#Tuple basics and unpacking
#Create a tuple with your name, age, city, and course. Print each element using indexing. Then unpack the tuple into 4 separate variables and print them with labels. Try to modify one element — observe and note what happens.

student_info = ("Hiya", 19 , "Rajkot", "Computer Science")

print("--- Indexing ---")
print(f"Name: {student_info[0]}")
print(f"Age: {student_info[1]}")
print(f"City: {student_info[2]}")
print(f"Course: {student_info[3]}")


name, age, city, course = student_info

print("\n--- Unpacked Variables ---")
print(f"Student Name: {name}")
print(f"Student Age: {age}")
print(f"Student City: {city}")
print(f"Student Course: {course}")

try:
    student_info[1] = 22
except TypeError as e:
    print(f"\n--- Modification Attempt ---")
    print(f"Error: {e}")

#Problem 05
#Student marks tracker
#Store marks of 5 students in a list. Calculate and print: total marks, average, highest mark, lowest mark, and whether any student scored above 90. Use loops and list methods

marks = [85, 92, 78, 60, 95]

total_marks = sum(marks)
average = total_marks / len(marks)
highest = max(marks)
lowest = min(marks)

print(f"Student Marks: {marks}")
print(f"Total: {total_marks}")
print(f"Average: {average}")
print(f"Highest: {highest}")
print(f"Lowest: {lowest}")


above_90 = False

for m in marks:
    if m > 90:
        above_90 = True
        break


if above_90:
    print("Did any student score above 90? Yes")
else:
    print("Did any student score above 90? No")

#Problem 06
#List as a stack
#Simulate a stack (last in, first out) using a list. Push 5 items onto the stack one by one, printing the stack after each push. Then pop all items one by one, printing the stack after each pop.

stack = []

# Push 5 items
for i in range(1, 6):
    stack.append(i)
    print("After push:", stack)

# Pop all items
while stack:
    stack.pop()
    print("After pop:", stack)

#Problem 07
#List comprehension intro
#Using list comprehension, create: a list of squares of numbers 1–10, a list of even numbers from 1–20, and a list of words longer than 4 characters from a given sentence. Print all three.

squares = [x**2 for x in range(1, 11)]

evens = [x for x in range(1, 21) if x % 2 == 0]

sentence = "Hello, How are you"
words = [word for word in sentence.split() if len(word) > 4]


print("Squares:", squares)
print("Even numbers:", evens)
print("Long words:", words)

#Problem 08
#Tuple as coordinates
#Create a list of 5 tuples, each representing (city_name, latitude, longitude). Print each city with its coordinates formatted neatly. Find and print the city with the highest latitude.

cities = [
    ("Delhi", 28.61, 77.21),
    ("Mumbai", 19.07, 72.87),
    ("Bangalore", 12.97, 77.59),
    ("Kolkata", 22.57, 88.36),
    ("Shimla", 31.10, 77.17)
]


for name, lat, lon in cities:
    print(f"{name}: Latitude = {lat}, Longitude = {lon}")


highest = max(cities, key=lambda x: x[1])
print("City with highest latitude:", highest[0])

#Problem 09
#List manipulation challenge
#Start with a list of 10 random numbers. Remove all duplicates (without using set()). Sort the result. Insert the number 99 at position 3. Print the final list and confirm 99 is at index 3.

nums = [5, 3, 7, 3, 9, 5, 1, 8, 7, 2]
print("Original:", nums)

unique = []
for n in nums:
    if n not in unique:
        unique.append(n)

unique.sort()

unique.insert(3, 99)

print("Final:", unique)
print("99 at index 3:", unique[3] == 99)

#Problem 10
#Matrix as nested list
#Create a 3x3 matrix as a nested list (list of lists). Print it formatted like a grid. Calculate and print the sum of each row. Find and print the largest element in the entire matrix.

matrix = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]


for row in matrix:
    print(*row)


for i, row in enumerate(matrix):
    print(f"Sum of row {i}:", sum(row))


largest = max(max(row) for row in matrix)
print("Largest element:", largest)