# -*- coding: utf-8 -*-
"""Loops.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jUsPDrZCvG18Tm6P_qbzmLav1zKXIGb5
"""

#Problem 01
#Count to N
#Take a number N as input. Print all numbers from 1 to N using a for loop. Then do the same using a while loop. Two separate outputs.

N = int(input("Enter a number: "))
for i in range(1, N+1):
    print(i)

N = int(input("Enter a number: "))
i = 1
while i <= N:
    print(i)
    i += 1

#Problem 02
#Sum and average
#Take N as input. Calculate the sum of all numbers from 1 to N using a loop. Then calculate and print the average. No formulas — use a loop to add one by one.

N = int(input("Enter a number: "))
sum = 0
for i in range(1, N+1):
    sum += i
print("The sum of all numbers from 1 to", N, "is", sum)

average = sum / N
print("The average of all numbers from 1 to", N, "is", average)

#Problem 03
#Multiplication table
#Take a number as input. Print its multiplication table from 1 to 10. Format it neatly: '7 x 3 = 21'.

N = int(input("Enter a number: "))
for i in range(1, 11):
    print(N, "x", i, "=", N*i)

#Problem 04
#Reverse countdown
#Take N as input. Print a countdown from N to 1 using a while loop, then print 'Blast off!' at the end. Then do the same using a for loop with range().

N = int(input("Enter a number: "))
while N > 0:
    print(N)
    N -= 1
print("Blast off!")

N = int(input("Enter a number: "))
for i in range(N, 0, -1):
    print(i)
print("Blast off!")

#Problem 05
#Factorial calculator
#Take a number N as input. Calculate its factorial using a loop. Print the result. Handle the edge case: factorial of 0 is 1.

N = int(input("Enter a number: "))
factorial = 1
for i in range(1, N+1):
    factorial *= i
print("The factorial of", N, "is", factorial)

#Problem 06
#Number pattern
#Print this pattern for N=5 using nested loops:
#1
#1 2
#1 2 3
#1 2 3 4
#1 2 3 4 5

N = 5

for i in range(1, N + 1):        # outer loop for rows
    for j in range(1, i + 1):    # inner loop for numbers
        print(j, end=" ")
    print()  # move to next line after each row

#Problem 07
#FizzBuzz
#Print numbers 1 to 50. But: print 'Fizz' for multiples of 3, 'Buzz' for multiples of 5, 'FizzBuzz' for multiples of both. This is one of the most famous coding problems — solve it cleanly.

for i in range(1, 51):
    if i % 3 == 0 and i % 5 == 0:
        print("FizzBuzz")
    elif i % 3 == 0:
        print("Fizz")
    elif i % 5 == 0:
        print("Buzz")
    else:
        print(i)

#Problem 08
#Digit sum and reversal
#Take a number as input. Using a while loop, calculate the sum of its digits. Also reverse the number. Print both. No string conversion allowed — use math only.

n = int(input("Enter a number: "))

original = n
sum_digits = 0
reverse = 0

while n > 0:
    digit = n % 10          # extract last digit
    sum_digits += digit     # add to sum
    reverse = reverse * 10 + digit  # build reverse
    n = n // 10             # remove last digit

print("Sum of digits:", sum_digits)
print("Reversed number:", reverse)

#Problem 09
#Prime number checker and lister
#First: take a number and check if it's prime. Then: print all prime numbers between 1 and 100. Two parts, both using loops.

num_to_check = int(input("Enter a number: "))
is_prime = True

if num_to_check < 2:
    is_prime = False
else:

    for i in range(2, num_to_check):
        if num_to_check % i == 0:
            is_prime = False
            break

if is_prime:
    print(f"{num_to_check} is prime.")
else:
    print(f"{num_to_check} is not prime.")



print("Primes between 1 and 100:")

for n in range(1, 101):

    if n < 2:
        continue


    is_prime_loop = True
    for i in range(2, n):
        if n % i == 0:
            is_prime_loop = False
            break

    if is_prime_loop:
        print(n, end=" ")

#Problem 10
#Simple number guessing game
#Set a secret number. Use a while loop to keep asking the user to guess. Tell them 'Too high', 'Too low', or 'Correct!' after each guess. Count how many attempts it took. Print the attempt count when they win.

secret_number = 42
guess = 0
attempts = 0

print("Welcome to the Guessing Game!")


while guess != secret_number:

    guess = int(input("Enter your guess: "))
    attempts = attempts + 1


    if guess > secret_number:
        print("Too high!")
    elif guess < secret_number:
        print("Too low!")
    else:
        print("Correct!")


print(f"It took you {attempts} attempts to win.")