# -*- coding: utf-8 -*-
"""Variables.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/191lkwMieTIJCVKAOGv6zt9MS_GnXTJe3
"""

#Problem 01
#Your personal info store
#Create variables for your name, age, city, and whether you're a student. Print each one with a label. Use the correct data type for each.

name = "Hiya"
age = 18
City = "Rajkot"
Student = True

print(type(name))
print(type(age))
print(type(City))
print(type(Student))

#Problem 02
#Type detective
#Create one variable of each type: int, float, str, bool. Print each variable AND its type using type(). Format the output neatly.

name = "Hiya"
age = 18
country = "India"
student = True
percentage = 98.99

print(name)
print(age)
print(country)
print(student)
print(percentage)
print(type(name))
print(type(age))
print(type(country))
print(type(student))
print(type(percentage))

#Problem 03
#Type conversion chain
#Start with the string '3.14'. Convert it to float, then to int, then back to string. Print the value AND type at each step. What do you notice about the int conversion?

pie = '3.14'
pie = float(pie)
print("Value of pie :", pie)
print("Type:", type(pie))
pie = int(pie)
print("Value of pie", pie)
print("Type:", type(pie))
pie = str(pie)
print("Value of pie", pie)
print("Type:", type(pie))

#Problem 04
#Smart receipt printer
#You bought 3 items. Store item name, quantity, and price per unit as separate variables. Calculate total cost. Print a formatted receipt using f-strings — show the item, qty, unit price, and total.

item1 = "Milk"
item2 = "Chocolates"
item3 = "cookies"

quat_item1 = 15
quat_item2 = 10
quat_item3 = 7

price_item1 = 20
price_item2 = 30
price_item3 = 4

total_cost = (quat_item1 * price_item1) + (quat_item2 * price_item2) + (quat_item3 * price_item3)

print("--------- RECEIPT ---------")
print(f"Item: {item1}, Quantity: {quat_item1}, Unit Price: ₹{price_item1}, Total: {quat_item1 * price_item1}")
print(f"Item: {item2}, Quantity: {quat_item2}, Unit Price: ₹{price_item2}, Total: {quat_item2 * price_item2}")
print(f"Item: {item3}, Quantity: {quat_item3}, Unit Price: ₹{price_item3}, Total: {quat_item3 * price_item3}")
print(f"Total Cost: {total_cost}")

#Problem 05
#String inspector
#Take any sentence as a string variable. Print: its length, it in ALL CAPS, it in all lowercase, the first word only, and whether the word 'python' appears in it (True/False).

sentence = "My name is Hiya"
print(len(sentence))
print(sentence.upper())
print(sentence.lower())
print(sentence.split()[0])
print('python' in sentence)

#Problem 06
#The swap
#Create two variables a = 10 and b = 25. Swap their values WITHOUT using a third variable. Print before and after.

a = (10)
b = (25)

print(type(a))
print(type(b))

print(a)
print(b)
a , b = b , a

print(a)
print(b)

#Problem 07
#BMI calculator
#Take weight (kg) and height (m) as float variables. Calculate BMI = weight / height². Print the result rounded to 2 decimal places, and a string category: Underweight, Normal, Overweight, or Obese.

weight = float(input("Enter your weight in kg: "))
height = float(input("Enter your height in meters:"))

BMI = weight / (height ** 2)

print(f"Your BMI is: {BMI:.2f}")
if (BMI < 18.5):
    print("Underweight")
elif (BMI >= 18.5 and BMI < 24.9):
    print("Normal")
elif (BMI >= 24.9 and BMI < 29.9):
    print("Overweight")
else :
    print("Obese")

#Problem 08
#Multiline f-string formatter
#Store a student's name, subject, marks (out of 100), and grade as variables. Print a formatted report card using an f-string that spans multiple lines. The output should look like an actual report card.

name = "Hiya"
subject = "Computer"
marks = 95
grade = "A"

print(f"""
--- REPORT CARD ---
Student Name: {name}
Subject:      {subject}
Marks:        {marks}
Grade:        {grade}

""")

#Problem 09
#The boolean logic tester
#Create variables: age=20, has_id=True, is_member=False. Print the result of at least 5 different boolean expressions using and, or, not. For each, also print a plain English explanation of what it checked.

age=20
has_id=True
is_member=False

print("Is this person an adult with valid ID?")
print(age >= 18 and has_id)

print("Is this person a member or an adult?")
print(is_member or age >= 18)

print("Is this person an adult and not a member?")
print(age >= 18 and not is_member)

print("Is this person an adult or a member?")
print(age >= 18 or is_member)

print("Is this person an adult and a member?")
print(age >= 18 and is_member)

print("Is this person not a member?")
print(not is_member)

#Problem 10
#Mini profile builder
#Ask yourself: what 6 pieces of data fully describe a person? Use at least 3 different data types. Store all 6, then print a nicely formatted profile. No input() — hardcode values. Make the output look presentable.

name = "Hiya"
age = 18
percent_12 = 98.99
percent_10 = 98.99
percent_graduation = 98.9
is_student = True

print("--------- PROFILE --------")
print(f"Name: {name}")
print(f"Age: {age}")
print(f"12th Percentage: {percent_12}")
print(f"10th Percentage: {percent_10}")
print(f"Graduation Percentage: {percent_graduation}")
print(f"Is Student: {is_student}")